name: cactus_example
description: Example app for the `cactus` library.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cactus:
    git:
      url: https://github.com/cactus-compute/cactus-flutter.git
      ref: main
  read_pdf_text: ^0.3.1
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.cactus_dev_config.json